### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by tlienart**
Patch release with a few minor docstring adjustments

### CODE REVIEW

**Comment by tlienart** [comment]
tests fail on nightly, maybe not important right now... am checking on 1.5.

**Comment by tlienart** [comment]
ok there's an issue on 1.5 as well; I suspect this is because 1.5 ships with modifications to the RNG and that there are a few stray tests that don't use StableRNGs; I'll check this later today if I have the time

**Comment by ablaom** [comment]
Strange. I cannot reproduce the 1.5 fail locally.

**Comment by ablaom** [comment]
Okay, this is more serious. StableRNGs *have* already been implented in the tests that fail, but they are not - how should I put this - stable 🤷‍♂️ 

Actually, I don't know yet if this is actually a StableRNGs issue or an issue with the Distributions.jl implementation of `rand` for `Distributions.Categorical` but the following runs on 1.5 while the assertion fails on 1.4:

```julia
using StableRNGs
using Distributions

d= Categorical([0.1, 0.2, 0.7])
rng = StableRNGs.StableRNG(600)
samples = rand(rng, d, 1000)
@assert Distributions.countmap(samples)[1] == 93
```

**Comment by ablaom** [comment]
It's StableRNGs: 

https://github.com/rfourquet/StableRNGs.jl/issues/4

**Comment by ablaom** [comment]
I think it's safe to merge this as the issue external and is only effecting the tests.

**Comment by ablaom** [comment]
FYI problem is with Distributions after all. They are using a depredated method from Random.

**Comment by ablaom** [comment]
https://github.com/JuliaStats/Distributions.jl/pull/1157

**Pull request merged**
