### PR TITLE
Bump LossFunctions v0.6 in Project.toml

### PR DESCRIPTION
**Pull request by juliohm**

### CODE REVIEW

**Comment by OkonSamuel** [comment]
@juliohm. Thanks

**Comment by juliohm** [comment]
Thank you @OkonSamuel for taking care of the tests, they are all green now. Could you please merge?

**Comment by tlienart** [comment]
thanks both

**Comment by juliohm** [comment]
Thank you @tlienart could you also release a new patch version?

**Comment by ablaom** [comment]
Will do

**Comment by ablaom** [comment]
https://github.com/JuliaRegistries/General/pull/12906

**Pull request merged**
