### PR TITLE
improve progressmeter display

### PR DESCRIPTION
**Pull request by OkonSamuel**
After my last PR i decided to push the limits of the progress meter display. This lead me to make the following four changes.
1. limit the buffer size of the `RemoteChannel` to a maximum of 1000. This is to limit the size of memory allocated which may affect performance of the program depending on the platform it is ran on. This choice follows that used in [ProgressMeter](https://github.com/timholy/ProgressMeter.jl) codebase.
2. Added a yield() in the case of `CPU1` and `CPUThreads`. This is to ensure smooth updating of the progress bar especially in the case of `CPUThreads.
3. Added an  Info message in the case of `CPUThreads` similar to `CPUProcesses` to tell the user the number of threads being used.
4. Add fallback to `CPU1` when `nthreads==1`. This was done to smooth-en the display in that case.

### CODE REVIEW

**Comment by ablaom** [comment]
Awesome! 💪

**Comment by ablaom** [comment]
Oops. This should have been merged to dev first. 

I'll just update dev manually. Last time I tried to fix this with a revert and new merge I got into trouble.

**Comment by ablaom** [comment]
Done.

**Comment by ablaom** [comment]
Now you have perfected these, would be great if you get a chance to consider  https://github.com/alan-turing-institute/MLJTuning.jl/issues/14 and https://github.com/alan-turing-institute/MLJTuning.jl/issues/15 ? 🥺

**Comment by OkonSamuel** [comment]
@ablaom  I'll take a look at it in my spare time.

**Pull request merged**
