### PR TITLE
Change `NTuple{<:T}` to `NTuple{N,<:T} where N`

### PR DESCRIPTION
**Pull request by giordano**
See https://github.com/JuliaLang/julia/issues/32170.  This will make the tests of `MLJ.jl` pass on Julia nightly

### CODE REVIEW

**Comment by giordano** [comment]
I think commits that have been pushed 20 minutes ago already contain this fix?

**Comment by ablaom** [comment]
Yes, I already noticed this error but hadn't pushed yet.

**Comment by ablaom** [comment]
However, nightly still failing. :-( Perhaps I missed something.

**Comment by giordano** [comment]
It's this issue: https://github.com/FugroRoames/TypedTables.jl/issues/48  The package needs a new stable version

**Pull request closed without merging**
