### PR TITLE
Documentation update for github pages

### PR DESCRIPTION
**Pull request by Arkoniak**
This is some initial setup for MLJBase API docs.

Notes:
- `matrix` has been changed to `jobs` per this recommendation: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/index.html#Travis-CI-1
- There are couple of warnings in docs build section, honestly do not know how to solve them, but it seems that final docs are fine
- One should of course setup DOCUMENTER_KEY and all other things in repo and travis CI. Also I do not know at what point travis creates `stable` version in `gh-pages`, I think simpliest solution is just to add copy of `dev` folder manually in `gh-pages` branch. 
- Unfortunately I do not know intrinsic details of MLJBase, so some docs were rather loosely put to categories, hope that's ok.

Result can be found here: https://arkoniak.github.io/MLJBase.jl/dev/

### CODE REVIEW

**Comment by Arkoniak** [comment]
Rebased PR to remove unnecessary commits.

**Comment by tlienart** [comment]
Thanks a lot for this!

**Comment by tlienart** [comment]
Now merged in master, the badges don't link to the docs but I suspect this is just because the docs have not been deployed yet (travis job not finished); thanks for your help!

**Comment by Arkoniak** [comment]
Well, they don't appear yet. 
Judging from https://travis-ci.com/github/alan-turing-institute/MLJBase.jl/jobs/299804378
it looks like DOCUMENTER_KEY is not set:

```
┌ Info: Deployment criteria for deploying devbranch build from Travis:
│ - ✔ ENV["TRAVIS_REPO_SLUG"]="alan-turing-institute/MLJBase.jl" occurs in repo="github.com/alan-turing-institute/MLJBase.jl.git"
│ - ✔ ENV["TRAVIS_PULL_REQUEST"]="false" is "false"
│ - ✔ ENV["TRAVIS_BRANCH"] matches devbranch="master"
│ - ✘ ENV["DOCUMENTER_KEY"] exists
│ - ✔ ENV["TRAVIS_EVENT_TYPE"]="pull_request" is not "cron"
└ Deploying: ✘
```

Adding `DOCUMENTER_KEY` and restarting job should help.

**Comment by tlienart** [comment]
Ah shit right thanks for pointing that out

**Comment by ablaom** [comment]
@Arkoniak Thanks for this. Very nice.

**Pull request merged**
