### PR TITLE
Update one_dimensional_ranges.jl

### PR DESCRIPTION
**Pull request by OkonSamuel**

### CODE REVIEW

**Comment by OkonSamuel** [comment]
@ablaom. It seems there are Compat issues with CSV

**Comment by ablaom** [comment]
Okay, thanks for flagging. I will investigate.

**Comment by ablaom** [comment]
Hopefully https://github.com/JuliaData/CSV.jl/pull/632 will get swift attention and resolve this. 

I haven't found an obvious workaround.  Pinning [deps] to versions last passing tests on master does not resolve the conflict. Previously, a pretty old version of CSV, namely 0.3.1 slipped through the sieve, but now CategoricalArrays ^0.8 is dissallowing it, for reasons I don't understand.

**Comment by ablaom** [comment]
Okay, this is embarrassing. Turns out we no longer use CSV in testing and can dump it. Working on a PR now.

**Comment by ablaom** [comment]
Resolved by https://github.com/alan-turing-institute/MLJBase.jl/pull/325

**Comment by ablaom** [comment]
@OkonSamuel To resolve the branch onflict you just need to choose the option without CSV.

**Comment by ablaom** [comment]
I guess this resolves #313. Does it also address https://github.com/alan-turing-institute/MLJ.jl/issues/548?

**Comment by OkonSamuel** [comment]
> I guess this resolves #313. Does it also address [alan-turing-institute/MLJ.jl#548](https://github.com/alan-turing-institute/MLJ.jl/issues/548)?

It resolves part of issue #548

**Comment by OkonSamuel** [comment]
that should fix it

**Comment by ablaom** [comment]
Thanks for this. I would like to review but it might take a day or so. Many thanks!

**Pull request merged**
