### PR TITLE
Add class_weights=... in evaluate! 

### PR DESCRIPTION
**Pull request by ablaom**
Continuation of #464 (conflicts resolved)

### CODE REVIEW

**Comment by ablaom** [comment]
@ven-k Are you ready for a review?

**Comment by ven-k** [comment]
I was trying to catch up with the new changes. A lot of new additions (makes it more robust now). 
Are there are any particular things you have in mind I should look at?

**Comment by ablaom** [comment]
No, nothing I can think of just now.  Its just that I have not yet done a detailed review of this PR yet and did not want to start until you are happy with what is there now. Just say the word and I'll review.

**Comment by ven-k** [comment]
It has the class_weights `evaluate!` function and resampling support. And subsequent tests. So I think I'm happy with this. (A huge thanks for StatisticalTraits)

I would be happy to add any more tests or any additional function that might be useful for this. You can review and let me know.

**Comment by ablaom** [comment]
@ven-k I've made a few tweaks and will merge this request. Many thanks for your contribution!

**Pull request merged**
