### PR TITLE
Fix indentation in ci.yml

### PR DESCRIPTION
**Pull request by ablaom**

### CODE REVIEW

**Comment by ablaom** [comment]
@DilumAluthge The docs are still auto-generating for non dev -> master PR's.

Any ideas?

**Comment by DilumAluthge** [comment]
Can you (temporarily) enable debug logging on this repo? You need to set two secrets: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging

When we are done debugging, you can delete those secrets.

**Comment by ablaom** [comment]
@DilumAluthge Okay it look like the statement after "if" needed indenting

**Comment by DilumAluthge** [comment]
Ugh. YAML. The whitespace (especially the indentation) absolutely kills me.

**Pull request closed without merging**
