### PR TITLE
Add the `:predict_joint` operation, and add composite and surrogate types for `JointProbabilistic`

### PR DESCRIPTION
**Pull request by DilumAluthge**
Please see: https://github.com/alan-turing-institute/MLJ.jl/issues/642

### CODE REVIEW

**Comment by ablaom** [comment]
Thanks for this @DilumAluthge . Looks good to me. 

For completeness we should probably make corresponding additions to this file providing extras types for composite models: 

https://github.com/alan-turing-institute/MLJBase.jl/blob/8e25843bee7d705354a97bc573850f3154682cbe/src/composition/abstract_types.jl#L2

Specifically, we should add:

```julia
abstract type JointProbabilisticComposite <: JointProbabilistic end
...
struct JointProbabilisticSurrogate <: JointProbabilistic end
```

And extend the aliases for the Union types there and add a constructor `JointProbabilistic` for `JointProbabilisticSurrogate()` instances. 

(Check my spelling!)

**Comment by DilumAluthge** [comment]
> Thanks for this @DilumAluthge . Looks good to me.
> 
> For completeness we should probably make corresponding additions to this file providing extras types for composite models:
> 
> https://github.com/alan-turing-institute/MLJBase.jl/blob/8e25843bee7d705354a97bc573850f3154682cbe/src/composition/abstract_types.jl#L2
> 
> Specifically, we should add:
> 
> ```julia
> abstract type JointProbabilisticComposite <: JointProbabilistic end
> ...
> struct JointProbabilisticSurrogate <: JointProbabilistic end
> ```
> 
> And extend the aliases for the Union types there and add a constructor `JointProbabilistic` for `JointProbabilisticSurrogate()` instances.
> 
> (Check my spelling!)

Sounds good, I'll add those changes!

**Comment by DilumAluthge** [comment]
@ablaom Take a look and see if there is anything I missed.

**Comment by DilumAluthge** [comment]
@ablaom @tlienart For `predict_joint`, we need to be able to pass keyword arguments.

The cleanest way to do this with the minimal amount of code changes was just to add kwarg support for all of the operations.

If you like, I can change it so that only `predict_joint` accepts kwargs.

**Comment by ablaom** [comment]
I'm sorry but that's a big change to allow kwargs in operations. There are now kwargs anywhere in the "model" interface. I don't like the extra complication to the operation overloadings. We've managed until now without it. What's your use case?  

Maybe you need another operation instead? Or you can control the behaviour of `predict_joint` with model hyperparameters?

**Comment by DilumAluthge** [comment]
I've removed the keyword arguments. Let me know if I missed one!

> (Or you can control the behaviour of predict_joint with model hyperparameters??)

I think this will be the best approach. We want to be able for users to say if they want predictions from e.g. (in the GLM example) `μ` or `y`. I think storing this preference in the model is fine.

**Comment by ablaom** [comment]
Possibly we can explore the new interface point in another thread. I'm happy to merge this PR when tests pass.

**Comment by DilumAluthge** [comment]
> Possibly we can explore the new interface point in another thread.

For sure. Chad and I are still experimenting in https://github.com/cscherrer/SossMLJ.jl, so there's lots of room to experiment and iterate.

That being said, it's coming together, so hopefully we'll have a full demo soon.

**Comment by DilumAluthge** [comment]
> I'm happy to merge this PR when tests pass.

That would be great!

**Comment by ablaom** [comment]
@DilumAluthge Thanks for making those extra changes.

**Pull request merged**
