### PR TITLE
Update train_test_pairs() for stratified CV 

### LINKED ISSUE #248: Tessellate levels across folds in stratified CV
While updating `train_test_pairs(::CV, ...)` I noticed an interesting behavior for stratified CV. It doesn't really matter much for large data sets, but for small data sets you can see a small anomaly. With the old `train_test_pairs(::CV, ...)`, if you take `y = categorical(collect('a'^4 * 'b'^4 * 'c'^4))` and use a 3-fold stratified CV, the classes would stack into the folds like this:

```
      c
c  c  c
      b
b  b  b
      a
a  a  a
```

where columns represent folds. With the new `train_test_pairs(::CV, ...)`, now they stack like this:

```
c
c  c  c
b
b  b  b
a
a  a  a
```

Probably the right way to stack them would be like this:

```
c  c  c
b  b  c
a  b  b
a  a  a
```

Here is one possible implementation to achieve the "tessellation" shown above:

```julia
function train_test_pairs4(stratified_cv::StratifiedCV, rows, X, y)

    st = scitype(y)
    st <: AbstractArray{<:Finite} ||
        error("Supplied target has scitpye $st but stratified "*
              "cross-validation applies only to classification problems. ")

    n_folds = stratified_cv.nfolds

    freq_given_level = countmap(y[rows])
    minimum(values(freq_given_level)) >= n_folds ||
        error("The number of observations for which the target takes on a "*
              "given class must, for each class, exceed `nfolds`. Try "*
              "reducing `nfolds`. ")

    if stratified_cv.shuffle
        rows=shuffle!(stratified_cv.rng, collect(rows))
    end

    n_obs = length(rows)
    obs_per_fold, rem = divrem(n_obs, n_folds)

    # The next two steps can be thought of as reshaping sorted_rows into a
    # ragged matrix with n_folds rows. Each row is a fold. There are
    # obs_per_fold+1 columns in the first r rows and obs_per_fold columns in
    # the remaining rows. Because sorted_rows is sorted by the category
    # levels, and because matrices are column-major, the levels are spread
    # evenly between the rows.

    sorted_rows = sort(rows; by=r -> y[r], alg=MergeSort)

    folds = map(1:n_folds) do i
        len = i <= rem ? obs_per_fold+1 : obs_per_fold
        ind = range(i; step=n_folds, length=len)
        sorted_rows[ind]
    end

    map(1:n_folds) do i
        train_folds = vcat(folds[ 1 : i-1 ], folds[ i+1 : end ])
        train = reduce(vcat, train_folds)
        (train, folds[i])
    end
end
```

### PR DESCRIPTION
**Pull request by CameronBieganek**
Fixes #248.

Benchmark between `dev` and this PR:

```julia
using BenchmarkTools

scv = StratifiedCV(nfolds=5);
N = 10_000_000;
rows = 1:(10N);
y = (
    vcat(fill(:a, N), fill(:b, 2N), fill(:c, 3N), fill(:d, 4N))
    |> shuffle
    |> categorical
);

@btime MLJBase.train_test_pairs_old($scv, $rows, $y);
#  14.767 s (1259 allocations: 21.88 GiB)

@btime MLJBase.train_test_pairs_new($scv, $rows, $y);
#  8.020 s (146 allocations: 4.84 GiB)
```

### CODE REVIEW

**Comment by CameronBieganek** [comment]
Hmmm, the diffs show some of your other commits. I guess maybe if you rebase `breaking` on `dev` then those diffs will disappear?

**Comment by CameronBieganek** [comment]
I just noticed `MLJBase.complement`. I could probably be using that at the end of `train_test_pairs`.

**Comment by ablaom** [comment]
Mmm. Rebased `breaking` onto `dev`. Issue may be that I prematurely bumped the version in Project.toml  (to 0.14.0). Maybe if you do that too the problem will go away?

**Comment by CameronBieganek** [comment]
Oh boy, here's the fun part... Messing around with git! 😁

Based on what I can see, it looks like maybe you didn't push your rebase of `breaking` to github? Unless I've missed a step in the git fetch/push/pull dance. Here's what I see when I look at the commit graph:

image

where you can see the extra commits that show up in this PR are on `dev` above the `breaking` branch.

**Comment by ablaom** [comment]
Oh yes, sorry. 😳  I did miss some steps and the merge conflicts are gone. Will now review.

**Pull request merged**
