### PR TITLE
Move from Travis CI to GitHub Actions CI 

### PR DESCRIPTION
**Pull request by DilumAluthge**
cc: @ablaom @tlienart

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@ablaom @tlienart This is ready to merge.

**Comment by DilumAluthge** [comment]
@ablaom Take a look at the `if` statement. We only build the docs if all three conditions are met:
1. The PR is NOT made from a fork
2. The base (target) branch is master
3. The head branch is dev

**Comment by ablaom** [comment]
@DilumAluthge Brilliant!

I'm going to rebase this PR to dev and see if docs are still generated.

**Comment by ablaom** [comment]
Mmm. Now no tests are being carried out.

**Pull request merged**
