### PR TITLE
fixes strange warnings

### PR DESCRIPTION
**Pull request by OkonSamuel**
see https://github.com/alan-turing-institute/MLJTuning.jl/pull/49#issuecomment-640089283

### CODE REVIEW

**Comment by OkonSamuel** [comment]
The Caveat to this is that it's slightly slower than the previous implementation if the time to run `evaluate` on each fold is large

**Comment by ablaom** [comment]
If "slightly slower" means within a factor of 1.5, I'm not fussed. Better safe than sorry. 

You could put a note in the code saying "This could be faster if ... But leads to warnings..."

**Comment by ablaom** [comment]
Mmm. Now that I look at the code, this adds quite a bit of complexity. Let's sleep on it.

**Comment by ablaom** [comment]
Okay, after sleeping on it I will go with your suggestion at the other issue to live with the warnings for now until we have a better understanding of what's causing them. 

Many thanks for this and well-done discovering the work-around. We may yet need to use it.

**Pull request closed without merging**
