### PR TITLE
Suppressed the display for @load_...

### PR DESCRIPTION
**Pull request by ven-k**
Closes the issue #226

### CODE REVIEW

**Comment by ven-k** [comment]
PS: This reverses the order of output.
from ```
X, y = @load_populardataset``` to ```
y, X = @load_populardataset``` .

**Comment by OkonSamuel** [comment]
Greetings @ven-k. 
Thanks for the PR. But i don't think this does what @ablaom wanted.
Currently state of things are shown by the code below.
```julia
 X, y = @load_iris1
(CategoricalArrays.CategoricalString{UInt32}["setosa", "setosa", "setosa", "setosa", "setosa",

 "setosa", "setosa", "setosa", "setosa", "setosa"  …  "virginica", "virginica", "virginica", "virginica", 

"virginica", "virginica", "virginica", "virginica", "virginica", "virginica"], (sepal_length = [5.1, 4.9, 4.7, 

4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9  …  6.7, 6.9, 5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9], sepal_width = [3.5, 

3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1  …  3.1, 3.1, 2.7, 3.2, 3.3, 3.0, 2.5, 3.0, 3.4, 3.0], petal_length 

= [1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5  …  5.6, 5.1, 5.1, 5.9, 5.7, 5.2, 5.0, 5.2, 5.4, 5.1], 

petal_width = [0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1  …  2.4, 2.3, 1.9, 2.3, 2.5, 2.3, 1.9, 2.0, 

2.3, 1.8]))
```
What is required is
```julia
 X, y = @load_iris1
```
And the PR doesn't do this.
One way to fix this is to wrap the output of `@load_iris` in a `struct` and use `Base.show` on that `struct`. (you also have to define some [interface](https://docs.julialang.org/en/v1/manual/interfaces/) methods)

**Comment by ablaom** [comment]
Many thanks to @ven-k, @OkonSamuel 

Yes, this is not nearly as straightforward to implement as I first imagined. I think I'd be happy to live with semicolons, as in `X, y = @load_iris;` and forgo the extra code complication. 

Any objection to me withdrawing my request and closing this PR?

**Comment by ven-k** [comment]
Thanks, @OkonSamuel.

Sure @ablaom. The extra code wouldn't make a sizeable difference.

**Pull request closed without merging**
